### ISSUE TITLE
on click of image , its is not opening , like tap or something .

### ISSUE THREAD

**Issue by amithit** [google-business-communications/bm-nodejs-appointment-bot#1]
i am using this json to send media , but when i click on that image , not able to open it.
var richcard = {

          standaloneCard:{
            cardContent: {
              'media': {
                'contentInfo': {
                  'forceRefresh': true,
                  'fileUrl': 'https://storage.googleapis.com/sample-logos/sf-office.png',
                },
                'height': 'TALL',
              }
            }
          }
        }
         sendResponse({
          messageId: uuidv4(),
          representative:getRepresentative(agentDetails),
    
          richCard: richcard
        }, conversationId,agentDetails);
      }

**Comment by thefalc** [comment]
In cards, the user cannot tap on an image. If you want that functionality, you can send an image on its own, not part of a card. See documentation here: https://developers.google.com/business-communications/business-messages/guides/build/send#images
